// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdxlryqaalecgssjkxqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkeGxyeXFhYWxlY2dzc2preHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODQyMDksImV4cCI6MjA2Mzc2MDIwOX0.5Q_Ab2fGhppCOycB4dG3YoQ5x3-fUoZCbUk_AYfdM_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);